corrijo los filtros del publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -9,21 +9,27 @@ jobs:
   check:
     runs-on: ubuntu-latest
     outputs:
-      status: ${{ steps.early.conclusion }}    
+      status: ${{ steps.success.ok }}    
     steps:
       - uses: actions/checkout@v4
       - name: Get package.json version
         id: get_package_version
-        run: echo "::set-output name=version::$(jq -r '.version' package.json)"    
+        run: echo "version=::$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"
       - name: Check versions from tag and package.json
         if: github.ref != format('refs/tags/v{0}', steps.get_package_version.outputs.version)
         run: |
-          echo "Error: Version does not matchs. Tag: (${{ github.ref }}),  package.json: (v${{ steps.get_package_version.outputs.version }})"
-          exit 1        
+          echo "Error: Versions does not match. Tag: (${{ github.ref }}),  package.json: (v${{ steps.get_package_version.outputs.version }})"
+          exit 1
+      - name: 
+        if: github.ref == format('refs/tags/v{0}', steps.get_package_version.outputs.version)
+        id: success
+        run: |
+          echo "Good: Versions match. (${{ github.ref }})"
+          echo "ok=ok" >> "$GITHUB_OUTPUT"
   publish:
     runs-on: ubuntu-latest
     needs: check
-    if: needs.check.outputs.status == 'success'    
+    if: needs.check.outputs.status == 'ok'    
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
